name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: publishPackage
    displayName: Publish Package to Nuget Library
    type: boolean
    default: false

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: Any CPU
  - name: buildConfiguration
    value: Release
  - group: 'Nuget - zbra-solutions'

steps:
- task: UseDotNet@2
  inputs:
    version: 8.0.x

- task: DotNetCoreCLI@2
  displayName: Dotnet Restore
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: Dotnet Build
  inputs:
    command: build
    projects: '**/*.csproj'
    workingDirectory: $(Build.SourcesDirectory)

- task: DockerCompose@1
  displayName: Docker Compose Up
  inputs:
    containerRegistryType: Container Registry
    dockerComposeFile: $(Build.SourcesDirectory)/.build/compose.yml
    action: Run services
    detached: true
    arguments: --force-recreate mongosetup
    projectName: "mongo-repository"
  
- task: DotNetCoreCLI@2
  displayName: Dotnet Test
  inputs:
    command: test
    projects: Mongo.Repository.Tests/Mongo.Repository.Tests.csproj

- task: DockerCompose@1
  condition: always()
  displayName: Docker Compose Down
  inputs:
    containerregistrytype: Container Registry
    dockerComposeFile: $(Build.SourcesDirectory)/.build/compose.yml
    action: Run a Docker Compose command
    dockerComposeCommand: down
    projectName: "mongo-repository"

- task: DotNetCoreCLI@2
  displayName: Nuget Pack
  inputs:
    command: pack
    packagesToPack: Mongo.Repository/Mongo.Repository.csproj
    versioningScheme: off

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" \
      --api-key $(NugetApiKey) \
      --source https://api.nuget.org/v3/index.json
  displayName: Nuget Push
  condition: eq(${{ parameters.publishPackage }}, true)
