name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: publishPackage
    displayName: Publish Package to Nuget Library
    type: boolean
    default: false

variables:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  inputs:
    version: 8.x

- task: NuGetToolInstaller@1
  displayName: Nuget Install

- task: NuGetAuthenticate@1
  displayName: Authenticate Nuget

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: Mongo.Repository/Mongo.Repository.sln
   
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    workingDirectory: $(Build.SourcesDirectory)
  
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: Mongo.Repository.Tests/Mongo.Repository.Tests.csproj

- task: DotNetCoreCLI@2
  displayName: Nuget Pack
  inputs:
    command: pack
    packagesToPack: Mongo.Repository/Mongo.Repository.csproj
    versioningScheme: off

- task: NuGetCommand@2
  displayName: Nuget push
  condition: eq(${{ parameters.publishPackage }}, true)
  inputs:
    command: push
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg
    nuGetFeedType: external
    publishFeedCredentials: Nuget
