version: '3.8'
services:
    mongodb1:
        image: mongo:4.4
        ports:
        - "27021:27017"
        entrypoint: [ '/usr/bin/mongod', '--replSet', 'rsmongo', '--bind_ip_all']
    mongodb2:
        image: mongo:4.4
        ports:
        - "27022:27017"
        entrypoint: [ '/usr/bin/mongod', '--replSet', 'rsmongo', '--bind_ip_all']
    mongodb3:
        image: mongo:4.4
        ports:
        - "27023:27017"
        entrypoint: [ '/usr/bin/mongod', '--replSet', 'rsmongo', '--bind_ip_all']
    mongosetup:
        image: "mongo-setup"
        build: "./mongo-setup"
        depends_on:
        - mongodb1
