version: '2'

services:
    mongo:
        image: mongo
        environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=dummy
        ports:
        - '27018:27017'
